### ISSUE TITLE
Add instructions on Docker usage modes

### ISSUE THREAD

**Issue by chgarth** [topology-tool-kit/topology-tool-kit.github.io#35]
These instructions should be listed before the "installation" instructions for Windows / Linux / MacOS so people can just try things out very quickly.

Also mention how to 
- [ ] run Docker server plus local GUI
- [ ] run TTK states
- [ ] run Python examples

**Comment by julien-tierny** [comment]
I'm going to go ahead and close this one.
I guess the current page (https://github.com/topology-tool-kit/ttk/tree/dev/scripts/docker) does the trick.
cheers
